/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MedicalRecords } from './MedicalRecords.js';
export * as factories from './factories/index.js';
export { MedicalRecords__factory } from './factories/MedicalRecords__factory.js';