/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MedicalRecordsInterface extends Interface {
    getFunction(nameOrSignature: "getAllRecordIds" | "getRecord" | "getTotalRecords" | "owner" | "recordExists" | "storeRecord" | "verifyRecord"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RecordStored" | "RecordVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'getAllRecordIds', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRecord', values: [string]): string;
encodeFunctionData(functionFragment: 'getTotalRecords', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordExists', values: [string]): string;
encodeFunctionData(functionFragment: 'storeRecord', values: [string, string, string, string]): string;
encodeFunctionData(functionFragment: 'verifyRecord', values: [string, string]): string;

    decodeFunctionResult(functionFragment: 'getAllRecordIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyRecord', data: BytesLike): Result;
  }

  
    export namespace RecordStoredEvent {
      export type InputTuple = [recordId: string, recordType: string, fileHash: string, uploadedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [recordId: string, recordType: string, fileHash: string, uploadedBy: string, timestamp: bigint];
      export interface OutputObject {recordId: string, recordType: string, fileHash: string, uploadedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordVerifiedEvent {
      export type InputTuple = [recordId: string, isValid: boolean, timestamp: BigNumberish];
      export type OutputTuple = [recordId: string, isValid: boolean, timestamp: bigint];
      export interface OutputObject {recordId: string, isValid: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MedicalRecords extends BaseContract {
    
    connect(runner?: ContractRunner | null): MedicalRecords;
    waitForDeployment(): Promise<this>;

    interface: MedicalRecordsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getAllRecordIds: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getRecord: TypedContractMethod<
      [_recordId: string, ],
      [[string, string, string, string, bigint] & {recordType: string, fileHash: string, fileUrl: string, uploadedBy: string, timestamp: bigint }],
      'view'
    >
    

    
    getTotalRecords: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordExists: TypedContractMethod<
      [_recordId: string, ],
      [boolean],
      'view'
    >
    

    
    storeRecord: TypedContractMethod<
      [_recordId: string, _recordType: string, _fileHash: string, _fileUrl: string, ],
      [void],
      'nonpayable'
    >
    

    
    verifyRecord: TypedContractMethod<
      [_recordId: string, _fileHash: string, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getAllRecordIds'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [_recordId: string, ],
      [[string, string, string, string, bigint] & {recordType: string, fileHash: string, fileUrl: string, uploadedBy: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalRecords'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordExists'): TypedContractMethod<
      [_recordId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'storeRecord'): TypedContractMethod<
      [_recordId: string, _recordType: string, _fileHash: string, _fileUrl: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyRecord'): TypedContractMethod<
      [_recordId: string, _fileHash: string, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'RecordStored'): TypedContractEvent<RecordStoredEvent.InputTuple, RecordStoredEvent.OutputTuple, RecordStoredEvent.OutputObject>;
getEvent(key: 'RecordVerified'): TypedContractEvent<RecordVerifiedEvent.InputTuple, RecordVerifiedEvent.OutputTuple, RecordVerifiedEvent.OutputObject>;

    filters: {
      
      'RecordStored(string,string,string,address,uint256)': TypedContractEvent<RecordStoredEvent.InputTuple, RecordStoredEvent.OutputTuple, RecordStoredEvent.OutputObject>;
      RecordStored: TypedContractEvent<RecordStoredEvent.InputTuple, RecordStoredEvent.OutputTuple, RecordStoredEvent.OutputObject>;
    

      'RecordVerified(string,bool,uint256)': TypedContractEvent<RecordVerifiedEvent.InputTuple, RecordVerifiedEvent.OutputTuple, RecordVerifiedEvent.OutputObject>;
      RecordVerified: TypedContractEvent<RecordVerifiedEvent.InputTuple, RecordVerifiedEvent.OutputTuple, RecordVerifiedEvent.OutputObject>;
    
    };
  }